from .magazine_views import (
    MagazineArticleAPIView,
    MagazineArticleView,
    MagazineArticlesAPIView,
    MagazineBookmarkAPIView,
    MagazineCommentAPIView,
    MagazineCompleteReadAPIView,
    MagazineHubAPIView,
    MagazineHubView,
    MagazineLikeAPIView,
    MagazineMetaAPIView,
    MagazineRateAPIView,
    MagazineRSSView,
    MagazineSearchAPIView,
    MagazineShareAPIView,
    MagazineSitemapView,
    MagazineViewAPIView,
)

__all__ = [
    "MagazineHubView",
    "MagazineArticleView",
    "MagazineSitemapView",
    "MagazineRSSView",
    "MagazineHubAPIView",
    "MagazineArticlesAPIView",
    "MagazineSearchAPIView",
    "MagazineMetaAPIView",
    "MagazineArticleAPIView",
    "MagazineViewAPIView",
    "MagazineLikeAPIView",
    "MagazineBookmarkAPIView",
    "MagazineShareAPIView",
    "MagazineCompleteReadAPIView",
    "MagazineRateAPIView",
    "MagazineCommentAPIView",
]
