# Generated by Django 6.0.7 on 2026-07-16 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('display_name', models.CharField(max_length=120, verbose_name='نام نمایشی')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('avatar', models.ImageField(blank=True, upload_to='barbers/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='سابقه (سال)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barber_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آرایشگر',
                'verbose_name_plural': 'آرایشگران',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='شروع')),
                ('end_time', models.TimeField(verbose_name='پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='barbers.barber', verbose_name='آرایشگر')),
            ],
            options={
                'verbose_name': 'ساعت کاری',
                'verbose_name_plural': 'ساعات کاری',
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('barber', 'weekday', 'start_time')},
            },
        ),
    ]
