# Generated by Django 6.0.7 on 2026-07-17 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('key', models.SlugField(default='home', help_text='مثلاً home — برای صفحه اصلی', max_length=60, unique=True, verbose_name='کلید')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='منتشر شده')),
                ('edition_label', models.CharField(blank=True, max_length=80, verbose_name='برچسب نسخه')),
                ('section_label', models.CharField(blank=True, max_length=80, verbose_name='برچسب بخش')),
                ('headline', models.TextField(help_text='هر خط را با Enter جدا کنید — خطوط به صورت بصری شکسته می\u200cشوند.', verbose_name='تیتر اصلی')),
                ('subtitle', models.TextField(blank=True, verbose_name='زیرتیتر')),
                ('story_body', models.TextField(blank=True, verbose_name='داستان برند')),
                ('quote_text', models.TextField(blank=True, verbose_name='نقل\u200cقول')),
                ('founder_name', models.CharField(blank=True, max_length=120, verbose_name='نام بنیان\u200cگذار')),
                ('founder_title', models.CharField(blank=True, max_length=120, verbose_name='عنوان بنیان\u200cگذار')),
                ('quote_signature', models.CharField(blank=True, max_length=160, verbose_name='امضای نقل\u200cقول')),
                ('bg_word_1', models.CharField(blank=True, max_length=40, verbose_name='واژه پس\u200cزمینه ۱')),
                ('bg_word_2', models.CharField(blank=True, max_length=40, verbose_name='واژه پس\u200cزمینه ۲')),
                ('bg_word_3', models.CharField(blank=True, max_length=40, verbose_name='واژه پس\u200cزمینه ۳')),
                ('bg_word_4', models.CharField(blank=True, max_length=40, verbose_name='واژه پس\u200cزمینه ۴')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='brand_story/', verbose_name='پرتره')),
                ('portrait_static', models.CharField(blank=True, max_length=255, verbose_name='پرتره JPG (static)')),
                ('portrait_webp_static', models.CharField(blank=True, max_length=255, verbose_name='پرتره WebP (static)')),
                ('portrait_lqip_static', models.CharField(blank=True, max_length=255, verbose_name='پرتره LQIP (static)')),
                ('portrait_alt', models.CharField(blank=True, max_length=220, verbose_name='متن جایگزین پرتره')),
                ('portrait_caption', models.CharField(blank=True, max_length=160, verbose_name='کپشن پرتره')),
                ('timeline_label', models.CharField(blank=True, max_length=80, verbose_name='برچسب مسیر')),
                ('values_label', models.CharField(blank=True, max_length=80, verbose_name='برچسب ارزش\u200cها')),
                ('cta_primary_label', models.CharField(blank=True, max_length=80, verbose_name='متن دکمه اصلی')),
                ('cta_primary_href', models.CharField(blank=True, help_text='مسیر مطلق، #anchor، یا نام URL مثل appointments:create', max_length=255, verbose_name='لینک دکمه اصلی')),
                ('cta_secondary_label', models.CharField(blank=True, max_length=80, verbose_name='متن دکمه فرعی')),
                ('cta_secondary_href', models.CharField(blank=True, help_text='مسیر مطلق، #anchor، یا نام URL', max_length=255, verbose_name='لینک دکمه فرعی')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='عنوان SEO')),
                ('seo_description', models.TextField(blank=True, verbose_name='توضیح SEO')),
            ],
            options={
                'verbose_name': 'داستان برند',
                'verbose_name_plural': 'داستان\u200cهای برند',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='BrandTimelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('number_label', models.CharField(max_length=8, verbose_name='شماره')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('portrait_effect', models.CharField(choices=[('focus', 'تمرکز چهره'), ('light', 'تغییر نور'), ('hair', 'تأکید مو'), ('bright', 'روشنایی کامل'), ('soft', 'نرمی'), ('none', 'بدون اثر')], default='none', max_length=20, verbose_name='اثر پرتره')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_steps', to='core.brandstory', verbose_name='داستان برند')),
            ],
            options={
                'verbose_name': 'گام مسیر',
                'verbose_name_plural': 'گام\u200cهای مسیر',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BrandValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=120, verbose_name='زیرعنوان')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.brandstory', verbose_name='داستان برند')),
            ],
            options={
                'verbose_name': 'ارزش برند',
                'verbose_name_plural': 'ارزش\u200cهای برند',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
