# Generated by Django 6.0.7 on 2026-07-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_brand_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandstory',
            name='portrait_index',
            field=models.CharField(blank=True, default='01', help_text='مثلاً 01 — میکرو\u200cتایپوگرافی کنار کپشن', max_length=12, verbose_name='شماره نمایش پرتره'),
        ),
    ]
