# Generated by Django 6.0.7 on 2026-08-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_homepage_pagecontent_sitesettings_homeassurancestep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='content_json',
            field=models.JSONField(blank=True, default=dict, help_text='JSON برای لیست\u200cها، UI رزرو، نشان\u200cها و متن\u200cهای جانبی', verbose_name='محتوای ساختاریافته'),
        ),
    ]
