# Generated by Django 6.1 on 2026-08-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pagecontent_content_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='reviews_cta_label',
            field=models.CharField(blank=True, max_length=80, verbose_name='نظرات — CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reviews_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='نظرات — برچسب'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reviews_lede',
            field=models.TextField(blank=True, verbose_name='نظرات — توضیح'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reviews_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='نظرات — عنوان'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='page',
            field=models.CharField(choices=[('catalog', 'کاتالوگ خدمات'), ('magazine', 'مجله'), ('booking', 'رزرو نوبت'), ('barbers', 'آرایشگران'), ('consultations', 'مشاوره'), ('reviews', 'نظرات')], max_length=40, unique=True, verbose_name='صفحه'),
        ),
    ]
