# Generated by Django 5.1.15 on 2026-07-17 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('key', models.SlugField(max_length=40, unique=True, verbose_name='کلید')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('card_label', models.CharField(blank=True, max_length=80, verbose_name='برچسب کارت')),
                ('icon', models.CharField(blank=True, help_text='نام آیکون یا ایموجی', max_length=80, verbose_name='آیکون')),
                ('accent_color', models.CharField(blank=True, default='#f7f4ef', help_text='مثل #f7f4ef', max_length=20, verbose_name='رنگ اختصاصی')),
                ('image_webp', models.CharField(blank=True, max_length=255, verbose_name='تصویر WebP')),
                ('image_jpg', models.CharField(blank=True, max_length=255, verbose_name='تصویر JPG')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('estimated_read_minutes', models.PositiveSmallIntegerField(default=5, verbose_name='مدت تقریبی مطالعه (دقیقه)')),
                ('booking_service_keys', models.JSONField(blank=True, default=list, help_text='مثلاً ["groom"] یا ["skin", "vip"]', verbose_name='کلیدهای سرویس رزرو مرتبط')),
                ('pdf_guide', models.FileField(blank=True, null=True, upload_to='consultations/guides/', verbose_name='PDF راهنمای کامل')),
                ('content_version', models.CharField(default='1.0', max_length=20, verbose_name='نسخه محتوا')),
            ],
            options={
                'verbose_name': 'دسته مشاوره',
                'verbose_name_plural': 'دسته\u200cهای مشاوره',
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('title', models.CharField(max_length=180, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن هشدار')),
                ('severity', models.CharField(choices=[('info', 'اطلاع'), ('warning', 'هشدار'), ('danger', 'بحرانی')], default='warning', max_length=20, verbose_name='شدت')),
                ('icon', models.CharField(blank=True, default='⚠', max_length=80, verbose_name='آیکون')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('show_in_booking', models.BooleanField(default=True, help_text='در مرحله تأیید رزرو نمایش داده شود', verbose_name='نمایش در خلاصه رزرو')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='consultations.consultationcategory', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'هشدار مهم',
                'verbose_name_plural': 'هشدارهای مهم',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('question', models.CharField(max_length=255, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='consultations.consultationcategory', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TipGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('key', models.SlugField(max_length=40, verbose_name='کلید')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('phase', models.CharField(choices=[('before', 'قبل از مراجعه'), ('day', 'روز مراجعه'), ('after', 'بعد از خدمات')], db_index=True, default='before', max_length=20, verbose_name='فاز')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('enabled', models.BooleanField(default=True, verbose_name='فعال')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_groups', to='consultations.consultationcategory', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'گروه نکات',
                'verbose_name_plural': 'گروه\u200cهای نکات',
                'ordering': ['sort_order', 'key'],
                'unique_together': {('category', 'key')},
            },
        ),
        migrations.CreateModel(
            name='ConsultationTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('title', models.CharField(max_length=180, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیح')),
                ('icon', models.CharField(blank=True, max_length=80, verbose_name='آیکون')),
                ('image', models.ImageField(blank=True, null=True, upload_to='consultations/tips/', verbose_name='تصویر آموزشی')),
                ('image_static', models.CharField(blank=True, help_text='اگر ImageField خالی باشد، از این مسیر static استفاده می\u200cشود', max_length=255, verbose_name='مسیر تصویر استاتیک')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب / اولویت')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('is_highlight', models.BooleanField(default=False, verbose_name='نکته مهم (هایلایت)')),
                ('video_url', models.URLField(blank=True, verbose_name='لینک ویدئو')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='consultations/pdfs/', verbose_name='فایل PDF')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='consultations/audio/', verbose_name='فایل صوتی')),
                ('external_link', models.URLField(blank=True, verbose_name='لینک مطالعه بیشتر')),
                ('content_version', models.CharField(default='1.0', max_length=20, verbose_name='نسخه محتوا')),
                ('read_seconds', models.PositiveSmallIntegerField(default=30, verbose_name='مدت مطالعه تقریبی (ثانیه)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='consultations.consultationcategory', verbose_name='دسته')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tips', to='consultations.tipgroup', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'نکته مشاوره',
                'verbose_name_plural': 'نکات مشاوره',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
