# Generated by Django 5.1.15 on 2026-07-17 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_consultation_guides'),
        ('consultations', '0001_consultation_guides'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('booking_service_key', models.SlugField(blank=True, max_length=40, verbose_name='کلید سرویس رزرو')),
                ('first_name', models.CharField(max_length=80, verbose_name='نام')),
                ('last_name', models.CharField(max_length=80, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(db_index=True, max_length=15, verbose_name='شماره تماس')),
                ('message', models.TextField(verbose_name='پیام / سوال')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='consultations/tickets/', verbose_name='فایل پیوست')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پاسخ'), ('answered', 'پاسخ داده شده'), ('closed', 'بسته')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('source', models.CharField(default='direct', help_text='booking | direct', max_length=40, verbose_name='منبع')),
                ('staff_notes', models.TextField(blank=True, verbose_name='یادداشت داخلی')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_tickets', to='appointments.appointment', verbose_name='رزرو مرتبط')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='consultations.consultationcategory', verbose_name='دسته مشاوره')),
            ],
            options={
                'verbose_name': 'تیکت مشاوره',
                'verbose_name_plural': 'تیکت\u200cهای مشاوره',
                'ordering': ['-created_at'],
            },
        ),
    ]
