# Generated by Django 6.0.7 on 2026-07-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationHubPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('key', models.SlugField(default='hub', help_text='مثلاً hub — صفحه لیست مشاوره\u200cها', max_length=40, unique=True, verbose_name='کلید')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('section_label', models.CharField(blank=True, max_length=80, verbose_name='برچسب بخش')),
                ('title', models.CharField(max_length=160, verbose_name='عنوان')),
                ('subtitle', models.TextField(blank=True, verbose_name='زیرعنوان')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='توضیح متا')),
                ('document_title', models.CharField(blank=True, help_text='اگر خالی باشد از title استفاده می\u200cشود', max_length=160, verbose_name='عنوان تب مرورگر')),
                ('empty_message', models.CharField(blank=True, max_length=255, verbose_name='پیام خالی بودن')),
                ('card_cta_label', models.CharField(blank=True, max_length=80, verbose_name='متن دکمه کارت')),
                ('card_stats_template', models.CharField(blank=True, help_text='از {tips} و {minutes} استفاده کنید', max_length=120, verbose_name='قالب آمار کارت')),
            ],
            options={
                'verbose_name': 'صفحه هاب مشاوره',
                'verbose_name_plural': 'صفحه هاب مشاوره',
            },
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='acknowledgment_error',
            field=models.CharField(blank=True, max_length=255, verbose_name='خطای عدم تأیید'),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='acknowledgment_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='متن تأیید راهنما'),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='confirm_guide_heading',
            field=models.CharField(blank=True, max_length=160, verbose_name='عنوان خلاصه در تأیید رزرو'),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='confirm_guide_link_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='لینک راهنمای کامل در تأیید'),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='gate_body',
            field=models.TextField(blank=True, verbose_name='متن گیت رزرو'),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='gate_eyebrow',
            field=models.CharField(blank=True, max_length=120, verbose_name='برچسب گیت رزرو'),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='gate_first_visit_body',
            field=models.TextField(blank=True, verbose_name='متن اولین مراجعه'),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='gate_first_visit_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان اولین مراجعه'),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='gate_primary_cta',
            field=models.CharField(blank=True, max_length=120, verbose_name='دکمه اصلی گیت'),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='gate_primary_cta_suffix',
            field=models.CharField(blank=True, max_length=80, verbose_name='پسوند CTA اصلی'),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='gate_primary_desc',
            field=models.CharField(blank=True, max_length=255, verbose_name='توضیح دکمه اصلی'),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='gate_primary_kicker',
            field=models.CharField(blank=True, max_length=80, verbose_name='برچسب پیشنهادی دکمه'),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='gate_secondary_cta',
            field=models.CharField(blank=True, max_length=120, verbose_name='دکمه فرعی گیت'),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='gate_secondary_desc',
            field=models.CharField(blank=True, max_length=255, verbose_name='توضیح دکمه فرعی'),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='gate_title',
            field=models.TextField(blank=True, verbose_name='عنوان گیت رزرو'),
        ),
        migrations.AlterField(
            model_name='consultationcategory',
            name='booking_service_keys',
            field=models.JSONField(blank=True, default=list, help_text='یک\u200cبه\u200cیک با سرویس رزرو — مثلاً ["vip"] یا ["groom"] یا ["skin"]', verbose_name='کلیدهای سرویس رزرو مرتبط'),
        ),
    ]
