# Generated by Django 6.0.7 on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0003_vip_category_and_gate_copy"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationhubpage",
            name="home_faq_description",
            field=models.TextField(blank=True, verbose_name="توضیح FAQ خانه"),
        ),
        migrations.AddField(
            model_name="consultationhubpage",
            name="home_faq_enabled",
            field=models.BooleanField(default=True, verbose_name="نمایش پرسش‌های پرتکرار در خانه"),
        ),
        migrations.AddField(
            model_name="consultationhubpage",
            name="home_faq_label",
            field=models.CharField(blank=True, max_length=80, verbose_name="برچسب FAQ خانه"),
        ),
        migrations.AddField(
            model_name="consultationhubpage",
            name="home_faq_link_label",
            field=models.CharField(blank=True, max_length=120, verbose_name="متن لینک FAQ خانه"),
        ),
        migrations.AddField(
            model_name="consultationhubpage",
            name="home_faq_title",
            field=models.CharField(blank=True, max_length=160, verbose_name="عنوان FAQ خانه"),
        ),
    ]
