# Generated by Django 6.0.7 on 2026-07-16 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی خدمت',
                'verbose_name_plural': 'دسته\u200cبندی خدمات',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('name', models.CharField(max_length=150, verbose_name='نام خدمت')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30, verbose_name='مدت (دقیقه)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.servicecategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
