# Generated by Django 6.0.7 on 2026-07-17 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی گالری',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای گالری',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GalleryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'برچسب گالری',
                'verbose_name_plural': 'برچسب\u200cهای گالری',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='زیرعنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیح کوتاه')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='portfolio/covers/', verbose_name='تصویر کاور')),
                ('cover_image_static', models.CharField(blank=True, max_length=255, verbose_name='مسیر کاور JPG/PNG')),
                ('cover_webp_static', models.CharField(blank=True, max_length=255, verbose_name='مسیر کاور WebP')),
                ('cover_avif_static', models.CharField(blank=True, max_length=255, verbose_name='مسیر کاور AVIF')),
                ('cover_lqip_static', models.CharField(blank=True, max_length=255, verbose_name='مسیر LQIP')),
                ('alt_text', models.CharField(blank=True, max_length=220, verbose_name='متن جایگزین')),
                ('video', models.FileField(blank=True, null=True, upload_to='portfolio/videos/', verbose_name='ویدئو')),
                ('video_url', models.URLField(blank=True, verbose_name='لینک ویدئو')),
                ('video_poster_static', models.CharField(blank=True, max_length=255, verbose_name='پوستر ویدئو (static)')),
                ('has_before_after', models.BooleanField(default=False, verbose_name='مقایسه قبل و بعد')),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='portfolio/before_after/', verbose_name='تصویر قبل')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='portfolio/before_after/', verbose_name='تصویر بعد')),
                ('before_image_static', models.CharField(blank=True, max_length=255, verbose_name='قبل (static)')),
                ('after_image_static', models.CharField(blank=True, max_length=255, verbose_name='بعد (static)')),
                ('before_alt', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین قبل')),
                ('after_alt', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین بعد')),
                ('problem', models.TextField(blank=True, verbose_name='مشکل / نیاز')),
                ('solution', models.TextField(blank=True, verbose_name='راه\u200cحل')),
                ('services_text', models.CharField(blank=True, max_length=255, verbose_name='خدمات انجام\u200cشده')),
                ('duration_text', models.CharField(blank=True, max_length=80, verbose_name='مدت زمان')),
                ('result', models.TextField(blank=True, verbose_name='نتیجه')),
                ('customer_review', models.TextField(blank=True, verbose_name='نظر مشتری')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='مکان')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='تاریخ اتمام')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='منتشر شده')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='ویژه')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='ترتیب')),
                ('cta_title', models.CharField(blank=True, default='از این نتیجه خوشتان آمد؟', max_length=180, verbose_name='عنوان CTA')),
                ('cta_consultation_label', models.CharField(blank=True, default='دریافت مشاوره', max_length=100, verbose_name='برچسب مشاوره')),
                ('cta_booking_label', models.CharField(blank=True, default='رزرو این خدمت', max_length=100, verbose_name='برچسب رزرو')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=170, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='portfolio.gallerycategory', verbose_name='دسته\u200cبندی')),
                ('related_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='catalog.serviceitem', verbose_name='خدمت مرتبط')),
                ('tags', models.ManyToManyField(blank=True, related_name='items', to='portfolio.gallerytag', verbose_name='برچسب\u200cها')),
            ],
            options={
                'verbose_name': 'آیتم گالری',
                'verbose_name_plural': 'آیتم\u200cهای گالری',
                'ordering': ['sort_order', '-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/gallery/', verbose_name='تصویر')),
                ('image_static', models.CharField(blank=True, max_length=255, verbose_name='مسیر static')),
                ('webp_static', models.CharField(blank=True, max_length=255, verbose_name='WebP static')),
                ('avif_static', models.CharField(blank=True, max_length=255, verbose_name='AVIF static')),
                ('lqip_static', models.CharField(blank=True, max_length=255, verbose_name='LQIP static')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='کپشن')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.galleryitem', verbose_name='آیتم')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'تصاویر گالری',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='galleryitem',
            index=models.Index(fields=['is_published', 'sort_order'], name='portfolio_g_is_publ_afd103_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryitem',
            index=models.Index(fields=['is_featured', 'is_published'], name='portfolio_g_is_feat_cac954_idx'),
        ),
    ]
