# Generated by Django 6.1 on 2026-08-12 22:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('key', models.SlugField(help_text='شناسه برنامه\u200cای — vip، groom، skin', max_length=40, unique=True, verbose_name='کلید')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=140, unique=True, verbose_name='اسلاگ')),
                ('lede', models.TextField(blank=True, verbose_name='توضیح')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='SEO عنوان')),
                ('seo_description', models.CharField(blank=True, max_length=300, verbose_name='SEO توضیح')),
                ('booking_service_key', models.SlugField(blank=True, help_text='برای لینک رزرو: /appointments/new/?service=', max_length=40, verbose_name='کلید سرویس رزرو')),
                ('consultation_category_key', models.SlugField(blank=True, help_text='برای لینک به /consultations/<key>/', max_length=40, verbose_name='کلید دسته مشاوره')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='ترتیب')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='منتشر شده')),
            ],
            options={
                'verbose_name': 'دسته نظر',
                'verbose_name_plural': 'دسته\u200cهای نظرات',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('title', models.CharField(max_length=220, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=240, verbose_name='اسلاگ')),
                ('body', models.TextField(help_text='۲ تا ۴ پاراگراف. پاراگراف\u200cها را با خط خالی جدا کنید.', verbose_name='متن نظر')),
                ('author_display_name', models.CharField(max_length=120, verbose_name='نام نمایشی')),
                ('author_role', models.CharField(blank=True, help_text='مثلاً داماد، مراجعه پوست، مهمان VIP', max_length=80, verbose_name='نقش / نسبت')),
                ('city', models.CharField(blank=True, default='اصفهان', max_length=80, verbose_name='شهر')),
                ('rating', models.PositiveSmallIntegerField(help_text='۱ تا ۵ — روی صفحه به\u200cصورت «۵ از ۵» دیده می\u200cشود', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('service_name', models.CharField(blank=True, help_text='برچسب نمایشی خدمت، مثلاً آرایش داماد', max_length=120, verbose_name='نام خدمت')),
                ('visited_on', models.DateField(blank=True, null=True, verbose_name='تاریخ مراجعه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='ویژه صفحه اصلی')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاریخ انتشار')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='ترتیب')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='SEO عنوان')),
                ('seo_description', models.CharField(blank=True, max_length=300, verbose_name='SEO توضیح')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='reviews/portraits/', verbose_name='پرتره')),
                ('portrait_static', models.CharField(blank=True, help_text='اگر ImageField خالی باشد از این مسیر static استفاده می\u200cشود', max_length=255, verbose_name='مسیر پرتره استاتیک')),
                ('source_note', models.CharField(blank=True, default='ثبت\u200cشده در سالن', max_length=120, verbose_name='منبع')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='reviews.reviewcategory', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'نظر مشتری',
                'verbose_name_plural': 'نظرات مشتریان',
                'ordering': ['sort_order', '-published_at', '-id'],
                'indexes': [models.Index(fields=['status', 'is_featured', '-published_at'], name='reviews_rev_status_ddd4be_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'slug'), name='reviews_unique_category_slug')],
            },
        ),
    ]
