# Generated by Django 6.0.7 on 2026-07-16 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbers', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='شروع نوبت')),
                ('ends_at', models.DateTimeField(verbose_name='پایان نوبت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('cancelled', 'لغو شده'), ('completed', 'انجام شده'), ('no_show', 'حاضر نشد')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('price_at_booking', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت در زمان رزرو')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='barbers.barber', verbose_name='آرایشگر')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='catalog.serviceitem', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['barber', 'starts_at'], name='appointment_barber__0f161a_idx'), models.Index(fields=['customer', 'starts_at'], name='appointment_custome_4010bc_idx')],
            },
        ),
    ]
