# Generated by Django 5.1.15 on 2026-07-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_booking_system'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_barber__0f161a_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_custome_4010bc_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_service_900cd6_idx',
            old_name='appointment_service_6c1e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_phone_bfa8d7_idx',
            old_name='appointment_phone_8f3a1c_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_booking_9dd0cc_idx',
            old_name='appointment_booking_2d4b9e_idx',
        ),
        migrations.AddField(
            model_name='appointment',
            name='guide_acknowledged',
            field=models.BooleanField(default=False, help_text='کاربر راهنمای قبل از مراجعه را پذیرفته است', verbose_name='تأیید مطالعه راهنما'),
        ),
    ]
