# Generated by Django 6.0.7 on 2026-08-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_consultation_guides'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('key', models.SlugField(default='site', max_length=40, unique=True, verbose_name='کلید')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('auto_confirm', models.BooleanField(default=True, help_text='اگر غیرفعال باشد نوبت با وضعیت «در انتظار» ثبت می\u200cشود.', verbose_name='تأیید خودکار نوبت')),
                ('cancel_before_hours', models.PositiveSmallIntegerField(default=24, verbose_name='حداقل فاصله لغو (ساعت)')),
                ('allow_customer_cancel', models.BooleanField(default=False, verbose_name='لغو توسط مشتری')),
                ('allow_customer_lookup', models.BooleanField(default=True, verbose_name='جستجوی نوبت توسط مشتری')),
                ('max_bookings_per_phone_per_day', models.PositiveSmallIntegerField(default=3, verbose_name='حداکثر نوبت روزانه هر شماره')),
                ('default_booking_lead_hours', models.PositiveSmallIntegerField(default=2, help_text='برای سرویس\u200cهایی که مقدار خاص ندارند.', verbose_name='پیش\u200cفرض فاصله تا نوبت (ساعت)')),
                ('default_booking_window_days', models.PositiveSmallIntegerField(default=45, verbose_name='پیش\u200cفرض بازه رزرو (روز)')),
                ('staff_notification_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل اطلاع\u200cرسانی')),
                ('cancellation_policy_text', models.TextField(blank=True, verbose_name='متن قوانین لغو')),
                ('confirmation_message', models.CharField(blank=True, max_length=300, verbose_name='پیام تأیید')),
                ('pending_message', models.CharField(blank=True, max_length=300, verbose_name='پیام در انتظار')),
            ],
            options={
                'verbose_name': 'تنظیمات رزرو',
                'verbose_name_plural': 'تنظیمات رزرو',
            },
        ),
    ]
